### ISSUE TITLE
Dependencies not loading when I locally compile the module

### ISSUE THREAD

**Issue by cubicgraphics** [200Tigersbloxed/VRCFTOmniceptModule#7]
I have been trying to get a locally compiled version of this module to load in the vrcft app, and vrcft output keeps informing me that it cannot find the file specified when it comes to loading the lib-client-csharp dll.
![image](https://github.com/200Tigersbloxed/VRCFTOmniceptModule/assets/79692655/005b0cd4-f920-494d-b094-ff4c8c945d15)
 I see that the dll file supplied in the releases seems to have all the namespaces included in it - but i don't know how to do this and googling has lead my no where.

I suppose what im asking is, how do i get the dll dependencies to work. I have my project set up basically as this git imported straight into visual studio.

(And for context)
What the latest released dll looks like
![image](https://github.com/200Tigersbloxed/VRCFTOmniceptModule/assets/79692655/2b22eb2f-f037-4433-838e-74ce33393313)

What mine looks like
![image](https://github.com/200Tigersbloxed/VRCFTOmniceptModule/assets/79692655/90f2e431-5ac3-44f1-a0ea-dee1a43b4fd6)

Any help would be appreciated

**Comment by 200Tigersbloxed** [comment]
> I suppose what im asking is, how do i get the dll dependencies to work. I have my project set up basically as this git imported straight into visual studio.

When building the dll, regardless of platform (core/framework), you must use an assembly bundler, such as [ILRepack](https://github.com/gluck/il-repack)

Here's my build script for ILRepack

```batch
ILRepack.exe /internalize:exclude.txt /out:out/VRCFTOmniceptModule.dll VRCFTOmniceptModule.dll AsyncIO.dll Google.Protobuf.dll lib-client-csharp.dll NetMQ.dll SemanticVersioning.dll
pause
```
and the exclude.txt

```
VRCFTOmniceptModule.*
```

This will allow these missing libraries to be not missing.

**Comment by cubicgraphics** [comment]
Thanks!
